# Generated by Django 4.2.7 on 2026-04-15 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommender', '0002_item_alter_userprofile_skill_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='interaction',
            name='watch_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.course'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
