# Generated by Django 4.2.7 on 2026-04-28 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommender', '0003_remove_interaction_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='interaction',
            unique_together={('user', 'course')},
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='viewed',
        ),
    ]
